---
title: "Practica_progra_3"
author: "Zulyn Méndez Ovares"
date: "2023-12-18"
output: html_document
---

```{r setup, include=FALSE}
library(shiny)
library(shinydashboard)
library(dplyr)
library(plotly)
library(DT)
library(openxlsx)
```

```{r}
spotify_2000_2023 <- read_delim("spotify_2000_2023.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)
View(spotify_2000_2023)


unique_years <- sort(unique(spotify_2000_2023$year))
unique_genres <- unique(spotify_2000_2023$top genre)

ui <- dashboardPage(
  dashboardHeader(title = "versus"),
  dashboardSidebar(
    selectInput("year_filter", "Filtrar por Año:", choices = unique_years, selected = unique_years),
    selectInput("genre_filter", "Filtrar por Género:", choices = unique_genres, selected = NULL),
    downloadButton("download_btn", "Descargar Información Filtrada")
  ),
  dashboardBody(
    box(
      title = "Versus de las canciones",
      status = "primary",
      solidHeader = TRUE,
      plotlyOutput("scatter_plot")
    ),
    box(
      title = "Comparaciones",
      status = "primary",
      solidHeader = TRUE,
      DTOutput("filtered_table")
    )
  )
)

server <- function(input, output) {
  output$scatter_plot <- renderPlotly({
    filtered_data <- spotify_2000_2023 |>
      filter(year == as.numeric(input$year_filter)) |>
      filter(top genre == input$genre_filter | is.null(input$genre_filter))

    plot_ly(filtered_data,
            x = ~danceability,
            y = ~popularity,
            text = ~title,
            type = "scatter",
            mode = "markers") |>
      layout(title = paste("Interactive Scatter Plot of Danceability vs Popularity (", input$year_filter, ")"),
             xaxis = list(title = "Danceability"),
             yaxis = list(title = "Popularity"))
  })

  output$filtered_table <- renderDT({
    filtered_data <- spotify_2000_2023 |>
      filter(year == as.numeric(input$year_filter)) |>
      filter(top genre == input$genre_filter | is.null(input$genre_filter))

    datatable(filtered_data, options = list(pageLength = 10))
  })

  output$download_btn <- downloadHandler(
    filename = function() {
      paste("filtered_data_", input$year_filter, ".xlsx", sep = "")
    },
    content = function(file) {
      filtered_data <- spotify_2000_2023 |>
        filter(year == as.numeric(input$year_filter)) |>
        filter(top genre == input$genre_filter | is.null(input$genre_filter))

      write.xlsx(filtered_data, file, rowNames = FALSE)
    }
  )
}

shinyApp(ui, server)

```

